### ISSUE TITLE
Configurable option to ensure dispatching events to handlers in the same order received

### ISSUE THREAD

**Issue by knivey** [aarondl/ultimateq#17]
With the option disabled handlers have a chance of being called in a different order than the order irc events were actually received in.

We should also provide a precise time for when we actually receive irc events to be available in the handler.

**Comment by aarondl** [comment]
The state of IRC at the current moment is the state of IRC at the current moment. Can't fix reality.

Someone may QUIT after they issue a command, the handlers should expect these kinds of failures and fail gracefully when querying the state database.
